TracktivityPets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TracktivityPets.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^fitbit/', include('fitapp.urls')),
    url(r'^', include('tracktivityPetsWebsite.urls', namespace="tracktivityPetsWebsite")),
)

fitapp/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',

    # OAuth authentication
    url(r'^login/$',
            views.login, name='fitbit-login'),
    url(r'^complete/$',
            views.complete, name='fitbit-complete'),
    url(r'^error/$',
            views.error, name='fitbit-error'),
    url(r'^logout/$',
            views.logout, name='fitbit-logout'),

    # Subscriber callback for near realtime updates
    url(r'^update/$',
            views.update, name='fitbit-update'),

    # Fitbit data retrieval
    url(r'^get_data/(?P<category>[\w]+)/(?P<resource>[/\w]+)/$',
            views.get_data, name='fitbit-data'),
    url(r'^get_steps/$', views.get_steps, name='fitbit-steps')
)

tracktivityPetsWebsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tracktivityPetsWebsite import views

urlpatterns = patterns('',
    #url(r'^$', 'views.home', name='home'),
    url(r'^login/', views.user_login, name='user_login'), #ie mysite.com/login/
    url(r'^logout/', views.user_logout, name='user_logout'), #ie mysite.com/logout/
    url(r'^', views.dashboard, name='dashboard'), #ie mysite.com/logout/
)

tracktivityPetsWebsite/models.py
from django.db import models

# Create your models here.

tracktivityPetsWebsite/views/login.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
import fitapp

def user_login(request):
    if  request.user.is_authenticated(): #if user is logged in
        fitbit_synched = False;
        if fitapp.utils.is_integrated(request.user):
            fitbit_synched = True
        return render(request, 'tracktivityPetsWebsite/login.html', {"synched": fitbit_synched})
    
    elif request.method == 'POST': #if http request was made with POST type
        try:
            username = request.POST['username'] #get and store username
        except:
            return render(request, 'tracktivityPetsWebsite/login.html', { "error_message": "No username" })
        
        try:
            password = request.POST['password'] #get and store password
        except:
            return render(request, 'tracktivityPetsWebsite/login.html', { "error_message": "No password" })
        
        user = authenticate(username=username, password=password) #django method to see if user exists in database
        if user is not None:
            if user.is_active: #if the account is activated
                login(request, user) #log the user into a session
                fitbit_synched = False;
                if fitapp.utils.is_integrated(user):
                    fitbit_synched = True
                return render(request, 'tracktivityPetsWebsite/login.html', {"synched": fitbit_synched})
            else:
                fitbit_synched = False;
                if fitapp.utils.is_integrated(user):
                    fitbit_synched = True
                return render(request, 'tracktivityPetsWebsite/login.html')
        else:
            return render(request, 'tracktivityPetsWebsite/login.html', { "error_message": "Incorrect username/password combination" }) #no user was found
        
    else:
        return render(request, 'tracktivityPetsWebsite/login.html')

tracktivityPetsWebsite/views/logout.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
    
def user_logout(request):
    if request.method == 'POST' and request.user.is_authenticated(): #if user is logged in
        logout(request) #log them out
        return HttpResponse("Logged out")
    else:
        return HttpResponse("No user to logout")
        

tracktivityPetsWebsite/templates/tracktivityPetsWebsite/login.html
{% comment %} if the user is logged in {% endcomment %}
{% if user.is_authenticated %}

	{% comment %} {{ var }} prints variable {% endcomment %}
	User is logged in and has username: {{ user.get_username }} 
	
	{% if not user.is_active %}
		<br/> User account is not active
	{% endif %}
	
	{% comment %} Button to logout {% endcomment %}
	<form action="{% url 'tracktivityPetsWebsite:user_logout' %}" method="POST">
		{% csrf_token %} 
		<input type="submit" name="logout_submit" value="Logout" /> 
	</form>
			{% if not synched %}
			<form action="/fitbit/login/" method="POST">
			{% csrf_token %}
			<input type="submit" name="link_fitbit" value="Link Fitbit Account" /> 
			</form>
		{% endif %}

{% comment %} Do this if user is not logged in {% endcomment %}	
{% else %} 
 
	{% if error_message %}
		{% comment %} Error made from previous POST {% endcomment %}
		Error: {{ error_message }} <br/><br/> 
	{% endif %}

	{% comment %} Generic login form {% endcomment %}
	<form action="{% url 'tracktivityPetsWebsite:user_login' %}" method="POST"> 
		{% csrf_token %}
		Username<br/>
		<input type="text" name="username" value="" />
		<br/>
		Password:<br/>
		<input type="password" name="password" value="" />
		<br/><br/>
		
		<input type="submit" name="login_submit" value="Submit" />
	</form>
{% endif %}